

dumpProject="project-prod"
dumpLogstore = ["test"]

receiveProject="project-dev"
#receiveLogstore = ["test","device-beautiful","favorite","ota","player","player-beautiful","search"]
receiveLogstore = ["test"]
